### ISSUE TITLE
bin dir should be prepended to PATH, not appended

### ISSUE THREAD

**Issue by wbolster** [sabslikesobs/pip.wtf#1]
summary says it all

**Comment by sabslikesobs** [comment]
And the rest of my doc says "you can do what you want if you want some different behavior". Wow!

**Comment by wbolster** [comment]
locally installed stuff _not_ picked up b/c system stuff masks it because the locally installed binaries come last in `$PATH`… is a huge wtf.

avoiding nasty surprises like that is kinda the point of this little hack in the first place, no?

anyway, seems being reasonable is not part of this project's philosophy 🤷🏼 bye

**Comment by sabslikesobs** [comment]
You convinced me, you wacky bastard! Now if only you could master basic grammar skills, I could only imagine your potential...!
