### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dbohdan** [sabslikesobs/pip.wtf#3]
The function `pip_wtf` is likely nontrivial enough to be copyrighted. Please add a license so others can freely use it. For short copy-pastable code I would recommend a [public-domain-equivalent license](https://en.wikipedia.org/wiki/Public-domain-equivalent_license). I like 0-clause BSD, but the name and the spirit of the project suggest WTFPL. :-)

**Comment by sabslikesobs** [comment]
I do not care.

**Comment by dbohdan** [comment]
Would you merge a PR adding a public domain-type license? The lack of a license means people can't legally use pip.wtf. As <https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository> says,

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

**Comment by sabslikesobs** [comment]
> The lack of a license means people can't legally use pip.wtf

I don't buy "you need a license!" culture, sorry. Licensing just means I'm giving a free in to every billion-dollar tech corporation out there. My website says: here's a cool thing you can do. That's an exchange between me and the reader. If they feel like they need a contract too, notarized by twenty years of lawyers, that's not my god damn problem.

**Comment by dbohdan** [comment]
Okay, in practical terms, those who want a license can use my venv function. Chances are, I can release it under what license I want. Since the conversation has gone into philosophy, though, I would like to present a counterargument. It is general, not specific to pip.wtf.

The problem with that line of thinking is that copyright applies with full strictness by default. In order to opt out, you must say you opt out in a way designed by lawyers.

When sharing nontrivial code without a license, what you are saying in legal terms is, "Here is a cool thing **I** can do. You can't do it." The reader has no legal right to use the code (implicit permissions aside). The reader is actually worse off for having read the copyrighted code. Even if they reimplement the idea independently, they are now "contaminated" by having seen the the original source. They can no longer claim a [clean-room implementation](https://en.wikipedia.org/wiki/Clean_room_design). Why is this bad? Legal ambiguity presents a greater risk for free software projects and hobbyists who can't defend themselves in court than for corporations that have retainer agreements with elite lawyers.
