### ISSUE TITLE
FYI: fades

### ISSUE THREAD

**Issue by dbohdan** [sabslikesobs/pip.wtf#4]
I read 

> it'll only work with a version of pip that's definitely not gonna be around on my ancient Debian VPS!

on the site and thought I'd mention [fades](https://github.com/PyAr/fades). It [has been in Debian's repositories](https://packages.debian.org/bookworm/fades) for several releases. Unlike pip-run, it caches virtualenvs.

(I am posting this as an issue because Discussions aren't enabled. Feel free to close immediately.)

**Comment by sabslikesobs** [comment]
Cool.
